%YAML:1.0
# The tum dataset directory with the associate.txt fiel, change it to yours! 
dataset_dir: ../dataset/rgbd_dataset_freiburg1_xyz

# The output trajectory file directory
output_file: ./output/output.txt

# camera intrinsics
# Freiburg 1 RGB
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 318.6
camera.cy: 255.3

camera.depth_scale: 5000

# frontend paras
number_of_features: 500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1

# backend paras
enable_local_optimization: 1
chi2_th: 1

# viewer paras
enable_viewer: 0